template_project/basic_app/urls.py
from django.urls import path
from basic_app import views

# TEMPLATE TAGGING
app_name = 'basic_app'

urlpatterns = [
    path('relative/', views.relative, name='relative'),
    path('other/', views.other, name='other'),
]

template_project/template_project/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('basic_app/', include('basic_app.urls')),
    path('admin/', admin.site.urls),
]

template_project/basic_app/models.py
from django.db import models

# Create your models here.

template_project/basic_app/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    index_dict = {'text': 'hello world', 'number': 100}
    return render(request, 'basic_app/index.html', context=index_dict)


def other(request):
    return render(request, 'basic_app/other.html')


def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')

template_project/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TITLE</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">BRAND</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home Page</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'basic_app:relative' %}">Relative</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">Admin</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'basic_app:other' %}">Other</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    {% block body_block %}
        {#    Anythin outside of this will be inherited if you extend!#}
    {% endblock %}
</div>
</body>
</html>

template_project/templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block body_block %}
    <h1>Welcome to Index</h1>
    <h1>{{ text | upper }}</h1>
    <h1>{{ number | cut:"0" }}</h1>
{% endblock %}

template_project/templates/basic_app/other.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block body_block %}
    <h1>Welcome to Other</h1>
    <h2>This is an example of template inheritance!</h2>
{% endblock %}

template_project/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block body_block %}
    <h1>Welcome to Relative URL Templates</h1>
{% endblock %}